/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once
#define VIAL_KEYBOARD_UID {0x9C, 0x27, 0x08, 0x26, 0xDE, 0x12, 0x9E, 0x2E}

#ifndef VIAL_INSECURE
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
#endif

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#ifdef RGB_MATRIX_ENABLE
//#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
//#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
//#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
//#undef ENABLE_RGB_MATRIX_BREATHING
//#undef ENABLE_RGB_MATRIX_BAND_SAT
//#undef ENABLE_RGB_MATRIX_BAND_VAL
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
//#undef ENABLE_RGB_MATRIX_CYCLE_ALL
//#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
//#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
//#undef ENABLE_RGB_MATRIX_RAINDROPS
//#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//#undef ENABLE_RGB_MATRIX_HUE_BREATHING
//#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
//#undef ENABLE_RGB_MATRIX_HUE_WAVE
//#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
//#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
//#undef ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef RGB_MATRIX_KEYPRESSES
#undef RGB_MATRIX_FRAMEBUFFER_EFFECTS
#undef RGB_MATRIX_KEYREACTIVE_ENABLED
#endif
